"""
Test Case Generation Skill - Generates comprehensive test cases from change analysis.

Uses Claude to intelligently create test cases based on code changes,
requirements, and risk assessment from the ChangeAnalysis.
"""

import json
import logging
from enum import Enum
from typing import Any, Dict, List, Optional

import anthropic
from pydantic import BaseModel, Field

from .code_analysis import ChangeAnalysis

logger = logging.getLogger(__name__)


class TestType(str, Enum):
    """Types of test cases."""
    FUNCTIONAL = "functional"
    REGRESSION = "regression"
    SMOKE = "smoke"
    PERFORMANCE = "performance"
    SECURITY = "security"
    INTEGRATION = "integration"
    BOUNDARY = "boundary"


class Priority(str, Enum):
    """Test case priority levels."""
    P0 = "P0"  # Must pass - blocking
    P1 = "P1"  # Should pass - high priority
    P2 = "P2"  # Normal priority
    P3 = "P3"  # Low priority / nice to have


class TestCase(BaseModel):
    """
    A single test case for QA execution.

    Generated by TestCaseGenSkill.generate().
    """
    id: str = Field(description="Test case identifier (e.g., TC-001)")
    title: str = Field(description="Descriptive test case title")
    type: TestType = Field(description="Type of test case")
    priority: Priority = Field(description="Test priority level")
    preconditions: str = Field(
        default="",
        description="Setup required before executing this test",
    )
    steps: List[str] = Field(
        default_factory=list,
        description="Step-by-step test execution instructions",
    )
    expected_result: str = Field(
        description="What should happen when the test passes",
    )
    test_data: str = Field(
        default="",
        description="Test data or values needed for this test case",
    )
    tags: List[str] = Field(
        default_factory=list,
        description="Tags for filtering/categorizing test cases",
    )
    estimated_minutes: int = Field(
        default=15,
        description="Estimated execution time in minutes",
    )


class TestCaseGenSkill:
    """
    Skill for generating comprehensive test cases from change analysis.

    Uses Claude to intelligently create test cases that cover:
    - Happy path scenarios
    - Edge cases and boundary conditions
    - Regression scenarios for affected areas
    - Smoke tests for quick validation
    - Security tests where applicable
    """

    def __init__(self, model: str = "claude-sonnet-4-6"):
        self._client = anthropic.Anthropic()
        self._model = model

    async def generate(
        self,
        change_analysis: ChangeAnalysis,
        requirements: Optional[str] = None,
        existing_test_cases: Optional[List[Dict[str, Any]]] = None,
        target_count: int = 8,
    ) -> List[TestCase]:
        """
        Generate test cases based on change analysis and requirements.

        Args:
            change_analysis: Structured analysis of code changes
            requirements: Optional requirements/acceptance criteria text
            existing_test_cases: Existing test cases to avoid duplicating
            target_count: Target number of test cases to generate

        Returns:
            List of TestCase objects ordered by priority
        """
        analysis_dict = change_analysis.model_dump()

        existing_str = ""
        if existing_test_cases:
            existing_str = f"\n\nExisting test cases (do not duplicate):\n{json.dumps(existing_test_cases, indent=2)}"

        requirements_str = f"\n\nRequirements/Acceptance Criteria:\n{requirements}" if requirements else ""

        prompt = f"""Based on the following code change analysis, generate {target_count} comprehensive test cases.

Change Analysis:
{json.dumps(analysis_dict, indent=2)}
{requirements_str}
{existing_str}

Generate test cases that cover:
1. Smoke tests (P0) - Basic functionality validation
2. Functional tests (P1) - Happy path scenarios
3. Boundary/Edge cases (P1-P2) - Input limits, empty values, special chars
4. Regression tests (P1-P2) - Ensure existing features still work
5. Error handling (P2) - How the system handles invalid inputs
6. Security tests (P1, if applicable) - Authentication, authorization, input validation

IMPORTANT: Respond ONLY with a valid JSON array of test case objects. No markdown, no explanations.

Format (JSON array):
[
  {{
    "id": "TC-001",
    "title": "Verify [feature] works correctly with [input]",
    "type": "smoke|functional|regression|performance|security|integration|boundary",
    "priority": "P0|P1|P2|P3",
    "preconditions": "What needs to be set up before this test",
    "steps": [
      "1. Navigate to [URL or screen]",
      "2. Enter [data] in [field]",
      "3. Click [button]",
      "4. Observe [result]"
    ],
    "expected_result": "Clear description of what should happen",
    "test_data": "Specific test data values needed",
    "tags": ["tag1", "tag2"],
    "estimated_minutes": 15
  }}
]

Prioritize P0 smoke tests first, then P1 functional/regression tests.
Make steps specific and actionable - a QA engineer should be able to follow them exactly."""

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )

            content = ""
            for block in response.content:
                if hasattr(block, "type") and block.type == "text":
                    content += block.text

            content = content.strip()
            # Strip markdown code blocks if present
            if content.startswith("```"):
                lines = content.split("\n")
                # Find first and last ``` markers
                start = 1
                end = len(lines)
                for i in range(len(lines) - 1, 0, -1):
                    if lines[i].strip() == "```":
                        end = i
                        break
                content = "\n".join(lines[start:end])

            test_cases_data = json.loads(content)

            # Validate and create TestCase objects
            test_cases = []
            for i, tc_data in enumerate(test_cases_data):
                try:
                    # Ensure required fields have defaults
                    tc_data.setdefault("id", f"TC-{i+1:03d}")
                    tc_data.setdefault("expected_result", "Test passes successfully")
                    tc_data.setdefault("estimated_minutes", 15)
                    tc_data.setdefault("tags", [])
                    tc_data.setdefault("test_data", "")
                    tc_data.setdefault("preconditions", "")
                    tc_data.setdefault("steps", ["Execute the test scenario"])

                    test_cases.append(TestCase(**tc_data))
                except Exception as e:
                    logger.warning(f"Failed to parse test case {i}: {e}")
                    continue

            # Sort by priority
            priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
            test_cases.sort(key=lambda tc: priority_order.get(tc.priority.value, 99))

            logger.info(f"Generated {len(test_cases)} test cases")
            return test_cases

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse test cases JSON: {e}")
            return self._generate_default_test_cases(change_analysis)
        except Exception as e:
            logger.error(f"Test case generation failed: {e}")
            return self._generate_default_test_cases(change_analysis)

    async def generate_regression_suite(
        self,
        affected_areas: List[str],
        existing_features: Optional[str] = None,
    ) -> List[TestCase]:
        """
        Generate a regression test suite for affected areas.

        Args:
            affected_areas: List of areas that might regress
            existing_features: Description of existing features to protect

        Returns:
            List of regression TestCase objects
        """
        areas_str = "\n".join(f"- {area}" for area in affected_areas)
        features_str = f"\n\nExisting features to protect:\n{existing_features}" if existing_features else ""

        prompt = f"""Generate regression test cases for the following affected areas:

{areas_str}
{features_str}

Create test cases that verify existing functionality still works correctly after the changes.
Focus on integration points and common user workflows.

Respond ONLY with a valid JSON array of test cases in this format:
[
  {{
    "id": "REG-001",
    "title": "Verify [existing feature] still works after changes",
    "type": "regression",
    "priority": "P1",
    "preconditions": "setup required",
    "steps": ["step 1", "step 2"],
    "expected_result": "existing functionality works as before",
    "test_data": "",
    "tags": ["regression"],
    "estimated_minutes": 10
  }}
]"""

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )

            content = ""
            for block in response.content:
                if hasattr(block, "type") and block.type == "text":
                    content += block.text

            content = content.strip()
            if content.startswith("```"):
                lines = content.split("\n")
                start = 1
                end = len(lines)
                for i in range(len(lines) - 1, 0, -1):
                    if lines[i].strip() == "```":
                        end = i
                        break
                content = "\n".join(lines[start:end])

            test_cases_data = json.loads(content)
            return [TestCase(**tc) for tc in test_cases_data]

        except Exception as e:
            logger.error(f"Regression suite generation failed: {e}")
            return []

    def _generate_default_test_cases(self, analysis: ChangeAnalysis) -> List[TestCase]:
        """Generate basic default test cases when AI generation fails."""
        test_cases = []

        # Basic smoke test
        test_cases.append(TestCase(
            id="TC-001",
            title="Smoke test: Verify application starts and basic navigation works",
            type=TestType.SMOKE,
            priority=Priority.P0,
            preconditions="Application deployed to test environment",
            steps=[
                "1. Navigate to the application URL",
                "2. Verify the application loads without errors",
                "3. Navigate through the main sections",
                "4. Verify no console errors",
            ],
            expected_result="Application loads successfully and is navigable",
            test_data="",
            tags=["smoke", "baseline"],
            estimated_minutes=10,
        ))

        # Regression test for each affected area
        for i, area in enumerate(analysis.test_scope[:3], start=2):
            test_cases.append(TestCase(
                id=f"TC-{i:03d}",
                title=f"Functional test: Verify {area}",
                type=TestType.FUNCTIONAL,
                priority=Priority.P1,
                preconditions="Test environment ready with test data",
                steps=[
                    f"1. Navigate to the {area} section",
                    "2. Perform the primary action",
                    "3. Verify the expected behavior",
                    "4. Check for any error messages",
                ],
                expected_result=f"The {area} functionality works as expected",
                test_data="Standard test data",
                tags=["functional"],
                estimated_minutes=20,
            ))

        return test_cases
