"""
Test Ticket Generation Skill - Generates comprehensive test tickets.

Combines PR information, change analysis, and test cases into a
structured test ticket ready for QA team assignment.
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

import anthropic
from pydantic import BaseModel, Field

from .code_analysis import ChangeAnalysis
from .test_case_gen import TestCase

logger = logging.getLogger(__name__)


class TestTicket(BaseModel):
    """
    A comprehensive test ticket for the QA team.

    Generated by TestTicketGenSkill.generate().
    """
    title: str = Field(description="Descriptive ticket title")
    pr_url: str = Field(description="URL of the pull request being tested")
    author: str = Field(description="Developer who submitted the PR")
    description: str = Field(
        description="What this change does and why it was made",
    )
    test_scope: str = Field(
        description="Clear description of what needs to be tested",
    )
    out_of_scope: str = Field(
        default="",
        description="What explicitly does NOT need to be tested",
    )
    risk_points: List[str] = Field(
        default_factory=list,
        description="Risk areas and things QA should pay special attention to",
    )
    test_cases: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of test cases to execute",
    )
    environment: str = Field(
        default="staging",
        description="Test environment to use",
    )
    environment_setup: List[str] = Field(
        default_factory=list,
        description="Steps to set up the test environment",
    )
    deadline: str = Field(
        default="",
        description="Deadline for completing testing (ISO format or relative)",
    )
    priority: str = Field(
        default="NORMAL",
        description="Ticket priority: URGENT/HIGH/NORMAL/LOW",
    )
    labels: List[str] = Field(
        default_factory=list,
        description="Labels/tags for the ticket",
    )
    notes: str = Field(
        default="",
        description="Any additional notes for the QA team",
    )
    created_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Ticket creation timestamp",
    )

    def to_markdown(self) -> str:
        """Convert the ticket to a Markdown-formatted string."""
        lines = [
            f"# 测试单: {self.title}",
            "",
            f"**PR链接**: {self.pr_url}",
            f"**提测人**: {self.author}",
            f"**优先级**: {self.priority}",
            f"**截止时间**: {self.deadline}",
            f"**测试环境**: {self.environment}",
            "",
            "## 功能描述",
            self.description,
            "",
            "## 测试范围",
            self.test_scope,
        ]

        if self.out_of_scope:
            lines.extend([
                "",
                "## 不测范围",
                self.out_of_scope,
            ])

        if self.risk_points:
            lines.extend(["", "## 风险点"])
            for risk in self.risk_points:
                lines.append(f"- {risk}")

        if self.environment_setup:
            lines.extend(["", "## 环境准备"])
            for step in self.environment_setup:
                lines.append(f"- {step}")

        if self.test_cases:
            lines.extend(["", "## 测试用例", ""])
            for tc in self.test_cases:
                lines.append(f"### {tc.get('id', 'TC')} - {tc.get('title', '')}")
                lines.append(f"**优先级**: {tc.get('priority', 'P2')} | **类型**: {tc.get('type', 'functional')}")
                if tc.get('preconditions'):
                    lines.append(f"**前置条件**: {tc['preconditions']}")
                lines.append("**步骤**:")
                for step in tc.get('steps', []):
                    lines.append(f"  {step}")
                lines.append(f"**期望结果**: {tc.get('expected_result', '')}")
                lines.append("")

        if self.notes:
            lines.extend(["", "## 备注", self.notes])

        return "\n".join(lines)


class TestTicketGenSkill:
    """
    Skill for generating comprehensive test tickets.

    Combines PR information, change analysis, and test cases into
    a well-structured test ticket ready for QA team consumption.
    """

    def __init__(self, model: str = "claude-sonnet-4-6"):
        self._client = anthropic.Anthropic()
        self._model = model

    async def generate(
        self,
        pr_info: Dict[str, Any],
        change_analysis: ChangeAnalysis,
        test_cases: List[TestCase],
        deadline_days: int = 2,
    ) -> TestTicket:
        """
        Generate a comprehensive test ticket.

        Args:
            pr_info: PR information dict with url, title, description, author
            change_analysis: Structured analysis of code changes
            test_cases: List of test cases to include
            deadline_days: Business days until testing deadline

        Returns:
            TestTicket dataclass with all ticket information
        """
        test_cases_data = [tc.model_dump() for tc in test_cases]
        analysis_data = change_analysis.model_dump()

        # Compute deadline
        deadline = (datetime.now() + timedelta(days=deadline_days)).strftime(
            "%Y-%m-%d"
        )

        prompt = f"""Based on the following PR information and change analysis, generate a comprehensive test ticket.

PR Information:
{json.dumps(pr_info, indent=2)}

Change Analysis:
{json.dumps(analysis_data, indent=2)}

Test Cases (already generated):
{json.dumps(test_cases_data, indent=2)}

Generate a test ticket in the following JSON format (respond ONLY with valid JSON):
{{
  "title": "清晰描述测试内容的标题 (in Chinese)",
  "pr_url": "{pr_info.get('url', '')}",
  "author": "developer name from PR",
  "description": "详细描述本次变更的功能和目的 (2-3 sentences in Chinese)",
  "test_scope": "明确说明需要测试的范围和内容",
  "out_of_scope": "明确说明不需要测试的内容",
  "risk_points": [
    "风险点1: 具体描述",
    "风险点2: 具体描述"
  ],
  "environment": "staging/production-like environment requirements",
  "environment_setup": [
    "setup step 1",
    "setup step 2"
  ],
  "deadline": "{deadline}",
  "priority": "URGENT|HIGH|NORMAL|LOW",
  "labels": ["relevant", "labels"],
  "notes": "任何额外的备注信息"
}}

The title and description should be in Chinese (中文) as this is for a Chinese-language DevOps team.
Risk points should be specific and actionable for QA engineers.
Priority should be HIGH if risk_level is HIGH, NORMAL otherwise."""

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )

            content = ""
            for block in response.content:
                if hasattr(block, "type") and block.type == "text":
                    content += block.text

            content = content.strip()
            if content.startswith("```"):
                lines = content.split("\n")
                start = 1
                end = len(lines)
                for i in range(len(lines) - 1, 0, -1):
                    if lines[i].strip() == "```":
                        end = i
                        break
                content = "\n".join(lines[start:end])

            ticket_data = json.loads(content)

            # Add the pre-generated test cases
            ticket_data["test_cases"] = test_cases_data

            # Ensure required fields
            ticket_data.setdefault("pr_url", pr_info.get("url", ""))
            ticket_data.setdefault("created_at", datetime.utcnow().isoformat())

            return TestTicket(**ticket_data)

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse ticket JSON: {e}")
            return self._generate_default_ticket(
                pr_info, change_analysis, test_cases, deadline
            )
        except Exception as e:
            logger.error(f"Ticket generation failed: {e}")
            return self._generate_default_ticket(
                pr_info, change_analysis, test_cases, deadline
            )

    async def enrich_ticket(
        self,
        ticket: TestTicket,
        additional_requirements: str,
    ) -> TestTicket:
        """
        Enrich an existing ticket with additional requirements.

        Args:
            ticket: Existing test ticket to enrich
            additional_requirements: Additional requirements or context to incorporate

        Returns:
            Updated TestTicket with enriched content
        """
        prompt = f"""Review and enrich the following test ticket with additional requirements.

Current ticket:
{json.dumps(ticket.model_dump(), indent=2)}

Additional requirements to incorporate:
{additional_requirements}

Return the complete updated ticket as JSON, incorporating the additional requirements
into the appropriate sections. Add any new risk points, update the test scope,
and add any necessary notes.

Respond ONLY with the updated ticket JSON."""

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=3000,
                messages=[{"role": "user", "content": prompt}],
            )

            content = ""
            for block in response.content:
                if hasattr(block, "type") and block.type == "text":
                    content += block.text

            content = content.strip()
            if content.startswith("```"):
                lines = content.split("\n")
                start = 1
                end = len(lines)
                for i in range(len(lines) - 1, 0, -1):
                    if lines[i].strip() == "```":
                        end = i
                        break
                content = "\n".join(lines[start:end])

            updated_data = json.loads(content)
            return TestTicket(**updated_data)

        except Exception as e:
            logger.error(f"Ticket enrichment failed: {e}")
            return ticket  # Return original if enrichment fails

    def _generate_default_ticket(
        self,
        pr_info: Dict[str, Any],
        change_analysis: ChangeAnalysis,
        test_cases: List[TestCase],
        deadline: str,
    ) -> TestTicket:
        """Generate a default ticket when AI generation fails."""
        risk_priority = {
            "HIGH": "URGENT",
            "MEDIUM": "HIGH",
            "LOW": "NORMAL",
        }

        return TestTicket(
            title=f"[提测] {pr_info.get('title', 'PR测试')}",
            pr_url=pr_info.get("url", ""),
            author=pr_info.get("author", "Unknown"),
            description=pr_info.get("description", "本次提测包含代码变更，请按照测试用例进行测试。"),
            test_scope="\n".join(change_analysis.test_scope) if change_analysis.test_scope
                      else "请测试本次PR变更涉及的所有功能模块",
            out_of_scope="与本次变更无关的功能模块",
            risk_points=change_analysis.risk_reasons or ["请关注主要功能流程"],
            test_cases=[tc.model_dump() for tc in test_cases],
            environment="staging",
            environment_setup=["1. 部署最新代码到测试环境", "2. 确认数据库迁移已执行", "3. 清除缓存"],
            deadline=deadline,
            priority=risk_priority.get(change_analysis.risk_level.value, "NORMAL"),
            labels=["dev-to-qa", change_analysis.risk_level.value.lower()],
            notes=change_analysis.implementation_notes or "",
        )
