apiVersion: v1
kind: Service
metadata:
  name: tool-service
  labels:
    app: tool-service
spec:
  selector:
    app: tool-service
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.toolService.port }}
  type: ClusterIP
